# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BFOSCCzU3V90Qw2KDMnAaL4darJ9tIyZ
"""

import pandas as pd
import numpy as np
import seaborn as sns

df= pd.read_csv("https://raw.githubusercontent.com/organisciak/names/master/raw/us-population-by-age-and-sex-2014.csv")
df

df.describe()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load your dataset into a DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/organisciak/names/master/raw/us-population-by-age-and-sex-2014.csv')

# Create a count plot for 'sex' column
sns.countplot(data=df, x='sex')

# Add labels and title
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Population Distribution by Gender')

# Show the chart
plt.show()

# Get unique values in the 'sex' column
unique_genders = df['sex'].unique()
print("Unique Genders:", unique_genders)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load your dataset into a DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/organisciak/names/master/raw/us-population-by-age-and-sex-2014.csv')

# Create a count plot for 'age' column
sns.countplot(data=df, x='age')

# Add labels and title
plt.xlabel('age')
plt.ylabel('Count')
plt.title('Population Distribution by Gender')

# Show the chart
plt.show()

# Get unique values in the 'age' column
unique_genders = df['age'].unique()
print("Unique age:", unique_age)

df= pd.read_csv("https://raw.githubusercontent.com/arienugroho050396/Airline-Passenger-Satisfaction/main/airline_passenger_satisfaction.csv")
df

df.describe()

# Create a count plot for 'sex' column
sns.countplot(data=df, x='Gender')

# Add labels and title
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Population Distribution by Gender')

# Show the chart
plt.show()

# Get unique values in the 'Gender' column
unique_genders = df['Gender'].unique()
print("Unique Genders:", unique_genders)

# Create a count plot for 'Age' column
sns.countplot(data=df, x='Age')

# Add labels and title
plt.xlabel('Age')
plt.ylabel('Count')
plt.title('Population Distribution by Gender')

# Show the chart
plt.show()

# Get unique values in the 'Age' column
unique_genders = df['Age'].unique()
print("Unique Age:", unique_Age)